# Empregabilidade em trabalhos de IA  e Ciência de Dados pelo Mundo // adrian (expansão da descrição (ex: falar sobre os dados, os objetivos com o dataset etc))

O Notebook tem como objetivo fazer uma análise exploratória de Dados para entender o cenário atual da área de Ciência de Dados e IA e as condições de seus trabalhadores. Deseja-se entender como que diferentes fatores como estudo, nível de experiência, nacionalidade e outros podem afetar o salário destes profissionais pensando em seu contexto., e respondendo perguntar pertinentes que podem nos escarecer certas questões.

## Inclusão das bibliotecas necessárias:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

## Tratamento e Limpeza dos Dados

Antes de tudo, é necessário inspecionar e preparar os dados. As etapas abaixo irão focar no pré-processamento antes das análises.

Plano de ação: Primeiro iremos carregar o dataset em uma variável df e ver a quantidade de linhas e colunas. Após isso, vamos ver se existem valores nulos ou duplicados e se sim analisaremos como vamos tratá-los. Também vamos mudar os tipos de dados para o que fizer sentido para o nosso propósito.

In [5]:
df = pd.read_csv('../data/raw/AI Job Market Dataset.csv')
df.head()

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2

Antes de tratar, precisamos entender o que temos: quantas linhas, quantas colunas, e qual o tipo de cada variável.

In [6]:
print(f"Dimensões do dataset: {df.shape[0]} linhas e {df.shape[1]} colunas\n")
print("Tipos de dados por coluna:")
print(df.dtypes)

Dimensões do dataset: 10345 linhas e 19 colunas

Tipos de dados por coluna:
job_id                  int64
job_title                 str
company_size              str
company_industry          str
country                   str
remote_type               str
experience_level          str
years_experience        int64
education_level           str
skills_python           int64
skills_sql              int64
skills_ml               int64
skills_deep_learning    int64
skills_cloud            int64
salary                  int64
job_posting_month       int64
job_posting_year        int64
hiring_urgency            str
job_openings            int64
dtype: object

In [7]:
nulos = df.isnull().sum()
print(nulos)

duplicatas = df.duplicated().sum()
print(duplicatas)

job_id                  0
job_title               0
company_size            0
company_industry        0
country                 0
remote_type             0
experience_level        0
years_experience        0
education_level         0
skills_python           0
skills_sql              0
skills_ml               0
skills_deep_learning    0
skills_cloud            0
salary                  0
job_posting_month       0
job_posting_year        0
hiring_urgency          0
job_openings            0
dtype: int64
0

In [8]:
df = df.drop_duplicates()
df = df.drop(columns=['job_id'])

print(f"Dataset após limpeza: {df.shape[0]} linhas e {df.shape[1]} colunas")

Dataset após limpeza: 10345 linhas e 18 colunas

In [ ]:
colunas_categoricas = ['job_title', 'company_size', 'company_industry', 'country', 'remote_type', 'experience_level', 'education_level', 'hiring_urgency']

for col in colunas_categoricas: df[col] = df[col].astype('category')

df['experience_level'] = pd.Categorical(df['experience_level'], categories=['Entry', 'Mid', 'Senior'], ordered=True)
df['education_level'] = pd.Categorical(df['education_level'], categories=['Bachelor', 'Master', 'PhD'], ordered=True)
df['company_size'] = pd.Categorical(df['company_size'], categories=['Startup', 'Medium', 'MNC', 'Enterprise'], ordered=True)

print(df.dtypes)

Tipos de dados após conversão:
job_title               category
company_size            category
company_industry        category
country                 category
remote_type             category
experience_level        category
years_experience           int64
education_level         category
skills_python              int64
skills_sql                 int64
skills_ml                  int64
skills_deep_learning       int64
skills_cloud               int64
salary                     int64
job_posting_month          int64
job_posting_year           int64
hiring_urgency          category
job_openings               int64
dtype: object

In [ ]:
df.describe()

,years_experience,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,job_openings
count,10345.000000,10345.000000,10345.000000,10345.000000,10345.000000,10345.000000,10345.00000,10345.000000,10345.000000,10345.00000
mean,6.950507,0.493088,0.503045,0.507878,0.498018,0.511455,113438.22726,6.502465,2023.000387,5.00406
std,4.320054,0.499976,0.500015,0.499962,0.500020,0.499893,31389.20106,3.473441,1.996856,2.58382
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45083.00000,1.000000,2020.000000,1.00000
25%,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,89715.00000,4.000000,2021.000000,3.00000
50%,7.000000,0.000000,1.000000,1.000000,0.000000,1.000000,113082.00000,6.000000,2023.000000,5.00000
75%,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,134894.00000,10.000000,2025.000000,7.00000
max,14.000000,1.000000,1.000000,1.000000,1.000000,1.000000,204143.00000,12.000000,2026.000000,9.00000

In [ ]:
print("Valores únicos por coluna categórica:")

for col in colunas_categoricas:
    print(f"[{col}] — {df[col].nunique()} categorias:")
    print(df[col].value_counts().to_string())
    print()

=== Valores únicos por coluna categórica ===

[job_title] — 6 categorias:
job_title
Business Analyst             1773
AI Engineer                  1742
Machine Learning Engineer    1740
Data Analyst                 1711
Data Scientist               1703
Data Engineer                1676

[company_size] — 4 categorias:
company_size
Startup       2656
MNC           2593
Medium        2548
Enterprise    2548

[company_industry] — 6 categorias:
company_industry
Technology    1787
E-commerce    1744
Finance       1724
Healthcare    1715
Education     1704
Retail        1671

[country] — 7 categorias:
country
Germany      1498
Singapore    1490
Canada       1488
UK           1485
India        1470
USA          1459
Australia    1455

[remote_type] — 3 categorias:
remote_type
Remote    3513
Hybrid    3420
Onsite    3412

[experience_level] — 3 categorias:
experience_level
Entry     3513
Senior    3420
Mid       3412

[education_level] — 3 categorias:
education_level
Master      3529
PhD         3425
Bachelor    3391

[hiring_urgency] — 3 categorias:
hiring_urgency
High      5195
Low       2756
Medium    2394

### Conclusão do Pré-processamento

O dataset possui 10.345 registros e 18 colunas (após remover o job_i`). Não foram encontrados valores nulos nem duplicatas, o que indica uma base bem estruturada. As principais ações realizadas foram a remoção da coluna job_id (sem valor de análise), ordenação e categorização de variáveis e revisão de valores nulos ou duplicados.

## Exploração das variáveis e suas relações:

Antes de responder as perguntas-chave, é importante explorar as variáveis do dataset para compreender suas relações entre si e as bases que a constitutem.

### Distribuição Salarial geral e entre subcategorias de trabalho: média, mediana, gráficos...

Aqui se quer compreender como é a distribuição salarial dependendo do título de trabalho, seja ele AI engineer, Business Analyst, e por aí vai. O motivo disso é que a distribuição de salário poderia variar dependendo da função performada, sendo difícil considerar tudo em um único grupo genérico.

Plano de ação:

In [ ]:
# código

Conclusão baseada no resultado:

### Habilidades mais e menos comuns: (skills)

(explicação do por que de se analisar isso)

Plano de ação: (ex: filtrar as variáveis com x e y e criar gráfico z ou extrair medidas w)

In [ ]:
# código

Conclusão baseada no resultado:

### Países com maiores distribuições

(explicação do por que de se analisar isso)

Plano de ação: (ex: filtrar as variáveis com x e y e criar gráfico z ou extrair medidas w)

In [ ]:
# código

Conclusão baseada no resultado:

### Distribução de nível de proficiência e educação vs anos de atuação

(explicação do por que de se analisar isso)

Plano de ação: (ex: filtrar as variáveis com x e y e criar gráfico z ou extrair medidas w)

In [ ]:
# código

Conclusão baseada no resultado:

### Setor de empresa vs trabalho remoto presencial...

(explicação do por que de se analisar isso)

Plano de ação: (ex: filtrar as variáveis com x e y e criar gráfico z ou extrair medidas w)

In [ ]:
# código

Conclusão baseada no resultado:

## Perguntas de Investigação:

##### 1. Qual é a dispersão salarial por nível de experiência e como que esses também se diferenciam baseado no nível de educação do profissional? // ramses

(explicação do por que de se analisar isso)

Hipótese sobre pergunta: É sensato acreditar que níveis de experiência e educação mais altos significam salários mais altos, porém a significância da diferença é algo que só a análise poderia responder

Plano de ação:

In [ ]:
# código

Conclusão baseada no resultado:

#### 2. Qual a correlação entre o tamanho da empresa e o tipo de trabalho realizado? (ex: Remoto ou presencial) // eduardo

(explicação do por que de se analisar isso)

Hipótese sobre pergunta: É possível que empresas maiores tenham o trabalho remoto como algo mais estruturado mas isso pode depender muito do tipo de empresa, onde que isso é analisado.

Plano de ação:

In [ ]:
# código

Conclusão baseada no resultado:

#### 3. Quais países estão com mais oportunidades de novas vagas e com urgência de mais profissionais? // pedro

(explicação do por que de se analisar isso)

Hipótese sobre pergunta: Países que estão focando no desenvolvimento da área de Ciências de Dados e IA provavelmente seriam os países que mais precisam de vagas preenchidas, muitas vezes países estão dispostos a fazer o investimento mas simplesmente não tem pessoas interessadas o suficiente na área.

Plano de ação:

In [ ]:
# código

Conclusão baseada no resultado:

## Observações e considerações (O que aprendemos dos dados):

## Conclusões: